//go:build darwin && arm64

package filesystem

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
	"sync"
	"time"

	appexport "github.com/irootkernel/mulgae/internal/app/export"
	"github.com/irootkernel/mulgae/internal/ports"
	"golang.org/x/sys/unix"
)

const (
	exportInstallDirectory = "store/export-installs"
	exportLockDirectory    = "store/locks"
	exportLockFile         = "export-install.lock"
)

var exportInstallProcessMu sync.Mutex

// ExportInstaller installs an immutable bundle and its receipt-bound manifest as
// one recoverable export pair. Its journal is intentionally internal to the
// approved root and is removed only after both destinations are verified.
type ExportInstaller struct {
	writer ports.SecureFileWriter
}

var _ appexport.ExportInstaller = (*ExportInstaller)(nil)

// NewExportInstaller constructs the filesystem-backed recoverable export
// installer. The writer is the sole byte-install authority.
func NewExportInstaller(writer ports.SecureFileWriter) (*ExportInstaller, error) {
	if nilInterface(writer) {
		return nil, fmt.Errorf("export installer: nil secure file writer")
	}
	return &ExportInstaller{writer: writer}, nil
}

type exportJournal struct {
	BundlePath   string `json:"bundle_path"`
	ManifestPath string `json:"manifest_path"`
	BundleSHA256 string `json:"bundle_sha256"`
	BundleBytes  int64  `json:"bundle_bytes"`
}

// Install serializes the store-scoped effect, durably records intent before
// either member, and adopts only exact regular-file matches on retry.
func (installer *ExportInstaller) Install(ctx context.Context, request appexport.ExportInstallRequest) (appexport.ExportInstallResult, error) {
	if installer == nil || nilInterface(installer.writer) || ctx == nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer: uninitialized installer or nil context")
	}
	if err := ctx.Err(); err != nil {
		return appexport.ExportInstallResult{}, err
	}
	if !request.Root.Valid() || !request.BundlePath.Valid() || !request.ManifestPath.Valid() || request.BundlePath == request.ManifestPath || request.MaxBytes <= 0 || len(request.Bundle) == 0 || len(request.SourceIDs) == 0 || request.ManifestForBundleReceipt == nil || int64(len(request.Bundle)) > request.MaxBytes {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer: invalid request")
	}

	exportInstallProcessMu.Lock()
	defer exportInstallProcessMu.Unlock()
	lock, err := acquireExportLock(ctx, request.Root, installer.writer)
	if err != nil {
		return appexport.ExportInstallResult{}, err
	}
	defer lock.release()

	key := exportInstallKey(request)
	journalPath, err := ports.NewSafeRelativePath(exportInstallDirectory + "/" + key + ".json")
	if err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer journal path: %w", err)
	}
	journal := exportJournal{request.BundlePath.String(), request.ManifestPath.String(), exportDigest(request.Bundle), int64(len(request.Bundle))}
	journalBytes, err := json.Marshal(journal)
	if err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer marshal journal: %w", err)
	}
	journalMaxBytes := request.MaxBytes
	if int64(len(journalBytes)) > journalMaxBytes {
		journalMaxBytes = int64(len(journalBytes))
	}
	if _, err := installer.writeOrAdopt(ctx, request.Root, journalPath, journalBytes, journalMaxBytes, "export_install_journal", request.SourceIDs); err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer record journal: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return appexport.ExportInstallResult{}, err
	}

	bundleReceipt, err := installer.writeOrAdopt(ctx, request.Root, request.BundlePath, request.Bundle, request.MaxBytes, "export_bundle", request.SourceIDs)
	if err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer bundle: %w", err)
	}
	manifestBytes, err := request.ManifestForBundleReceipt(bundleReceipt)
	if err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer manifest: %w", err)
	}
	if len(manifestBytes) == 0 || int64(len(manifestBytes)) > request.MaxBytes {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer manifest: invalid generated bytes")
	}
	if err := ctx.Err(); err != nil {
		return appexport.ExportInstallResult{}, err
	}
	manifestReceipt, err := installer.writeOrAdopt(ctx, request.Root, request.ManifestPath, manifestBytes, request.MaxBytes, "export_manifest", request.SourceIDs)
	if err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer manifest install: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return appexport.ExportInstallResult{}, err
	}
	if err := removeExportJournal(request.Root, journalPath); err != nil {
		return appexport.ExportInstallResult{}, fmt.Errorf("export installer cleanup journal: %w", err)
	}
	return appexport.ExportInstallResult{BundleReceipt: bundleReceipt, ManifestReceipt: manifestReceipt, ManifestBytes: append([]byte(nil), manifestBytes...)}, nil
}

func (installer *ExportInstaller) writeOrAdopt(ctx context.Context, root ports.AnchoredRoot, destination ports.SafeRelativePath, contents []byte, maximum int64, channel string, sourceIDs []string) (ports.SecureWriteReceipt, error) {
	operations := defaultSecureWriterOperations()
	if writer, ok := installer.writer.(*SecureWriter); ok {
		operations = writer.operationSet()
	}
	if receipt, err := verifyAndSyncExportFile(root, destination, contents, maximum, channel, sourceIDs, operations); err == nil {
		return receipt, nil
	} else if !errors.Is(err, unix.ENOENT) {
		return ports.SecureWriteReceipt{}, err
	}
	writeRequest, err := ports.NewSecureWriteRequest(root, destination, channel, bytes.NewReader(contents), maximum, sourceIDs, func(error) {})
	if err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	receipt, _, err := installer.writer.Write(ctx, writeRequest)
	if err == nil {
		return receipt, nil
	}
	if err := ctx.Err(); err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	// EEXIST is intentionally resolved only by a fresh anchored verification.
	if errors.Is(err, unix.EEXIST) {
		if verified, verifyErr := verifyAndSyncExportFile(root, destination, contents, maximum, channel, sourceIDs, operations); verifyErr == nil {
			return verified, nil
		}
	}
	return ports.SecureWriteReceipt{}, err
}

func verifyAndSyncExportFile(root ports.AnchoredRoot, path ports.SafeRelativePath, want []byte, maximum int64, channel string, sourceIDs []string, operations secureWriterOperations) (ports.SecureWriteReceipt, error) {
	parents, name, err := splitDestination(path)
	if err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	operations = operations.withDefaults()
	directory, err := walkPrivateDirectoryWithOperations(root, parents, false, operations)
	if err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	defer closeFD(directory)
	rootFD, err := openAnchoredRoot(root)
	if err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	rootIdentity, err := privateDirectoryIdentityForFD(rootFD)
	closeFD(rootFD)
	if err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export root identity: %w", err)
	}
	directoryIdentity, err := privateDirectoryIdentityForFD(directory)
	if err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination directory: %w", err)
	}
	if _, err := verifyExportFileAt(directory, name, root, path, want, maximum, channel, sourceIDs); err != nil {
		return ports.SecureWriteReceipt{}, err
	} else if err := revalidateExportDirectory(root, rootIdentity, parents, directoryIdentity, operations); err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination directory before sync: %w", err)
	} else if err := operations.fsync(directory); err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("sync adopted export destination directory: %w", err)
	} else if err := revalidateExportDirectory(root, rootIdentity, parents, directoryIdentity, operations); err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination directory after sync: %w", err)
	} else if verified, err := verifyExportFileAt(directory, name, root, path, want, maximum, channel, sourceIDs); err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify adopted export destination after sync: %w", err)
	} else {
		return verified, nil
	}
}
func revalidateExportDirectory(root ports.AnchoredRoot, rootIdentity privateDirectoryIdentity, parents []string, directoryIdentity privateDirectoryIdentity, operations secureWriterOperations) error {
	rootFD, err := openAnchoredRoot(root)
	if err != nil {
		return err
	}
	actualRootIdentity, identityErr := privateDirectoryIdentityForFD(rootFD)
	closeErr := unix.Close(rootFD)
	if identityErr != nil {
		return errors.Join(identityErr, closeErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close export root revalidation: %w", closeErr)
	}
	if actualRootIdentity != rootIdentity {
		return fmt.Errorf("anchored root namespace changed")
	}
	return revalidatePrivateDirectory(root, parents, directoryIdentity, operations)
}

func verifyExportFileAt(directory int, name string, root ports.AnchoredRoot, path ports.SafeRelativePath, want []byte, maximum int64, channel string, sourceIDs []string) (ports.SecureWriteReceipt, error) {
	fd, err := unix.Openat(directory, name, unix.O_RDONLY|unix.O_NONBLOCK|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	defer closeFD(fd)
	if err := verifyPrivateRegularFile(fd); err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination: %w", err)
	}
	stat := unix.Stat_t{}
	if err := unix.Fstat(fd, &stat); err != nil {
		return ports.SecureWriteReceipt{}, err
	}
	if stat.Size < 0 || stat.Size > maximum || stat.Size != int64(len(want)) {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination: byte length mismatch")
	}
	actual, err := io.ReadAll(io.LimitReader(unixFile{fd: fd}, maximum+1))
	if err != nil {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination: read: %w", err)
	}
	if !bytes.Equal(actual, want) {
		return ports.SecureWriteReceipt{}, fmt.Errorf("verify export destination: content mismatch")
	}
	return ports.NewSecureWriteReceipt(root, path, exportDigest(want), int64(len(want)), channel, sourceIDs)
}

type unixFile struct{ fd int }

func (file unixFile) Read(p []byte) (int, error) {
	n, err := unix.Read(file.fd, p)
	if err == nil && n == 0 {
		return 0, io.EOF
	}
	return n, err
}

func exportDigest(bytes []byte) string {
	sum := sha256.Sum256(bytes)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func exportInstallKey(request appexport.ExportInstallRequest) string {
	input := request.BundlePath.String() + "\x00" + request.ManifestPath.String() + "\x00" + exportDigest(request.Bundle)
	sum := sha256.Sum256([]byte(input))
	return hex.EncodeToString(sum[:])
}

type exportLock struct{ rootFD, directory, file int }

func acquireExportLock(ctx context.Context, root ports.AnchoredRoot, writer ports.SecureFileWriter) (*exportLock, error) {
	lockPath, err := ports.NewSafeRelativePath(exportLockDirectory)
	if err != nil {
		return nil, err
	}
	if err := writer.EnsurePrivateDir(root, lockPath); err != nil {
		return nil, fmt.Errorf("export lock directory: %w", err)
	}
	rootFD, err := openAnchoredRoot(root)
	if err != nil {
		return nil, err
	}
	directory, err := walkPrivateDirectory(root, strings.Split(exportLockDirectory, "/"), false)
	if err != nil {
		closeFD(rootFD)
		return nil, err
	}
	file, err := unix.Openat(directory, exportLockFile, unix.O_RDWR|unix.O_CREAT|unix.O_EXCL|unix.O_NOFOLLOW|unix.O_CLOEXEC, privateFileMode)
	created := err == nil
	if errors.Is(err, unix.EEXIST) {
		file, err = unix.Openat(directory, exportLockFile, unix.O_RDWR|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	}
	if err != nil {
		closeFD(directory)
		closeFD(rootFD)
		return nil, fmt.Errorf("open export lock: %w", err)
	}
	if created {
		if err := unix.Fsync(directory); err != nil {
			closeFD(file)
			closeFD(directory)
			closeFD(rootFD)
			return nil, fmt.Errorf("sync created export lock: %w", err)
		}
	}
	if err := verifyPrivateRegularFile(file); err != nil {
		closeFD(file)
		closeFD(directory)
		closeFD(rootFD)
		return nil, err
	}
	lock := &exportLock{rootFD, directory, file}
	for {
		if err := ctx.Err(); err != nil {
			lock.release()
			return nil, err
		}
		if err := unix.Flock(file, unix.LOCK_EX|unix.LOCK_NB); err == nil {
			return lock, nil
		} else if !errors.Is(err, unix.EWOULDBLOCK) && !errors.Is(err, unix.EAGAIN) && !errors.Is(err, unix.EINTR) {
			lock.release()
			return nil, err
		}
		timer := time.NewTimer(10 * time.Millisecond)
		select {
		case <-ctx.Done():
			timer.Stop()
			lock.release()
			return nil, ctx.Err()
		case <-timer.C:
		}
	}
}
func (lock *exportLock) release() {
	if lock == nil {
		return
	}
	if lock.file >= 0 {
		_ = unix.Flock(lock.file, unix.LOCK_UN)
		closeFD(lock.file)
		lock.file = -1
	}
	closeFD(lock.directory)
	closeFD(lock.rootFD)
	lock.directory, lock.rootFD = -1, -1
}

func removeExportJournal(root ports.AnchoredRoot, path ports.SafeRelativePath) error {
	parents, name, err := splitDestination(path)
	if err != nil {
		return err
	}
	directory, err := walkPrivateDirectory(root, parents, false)
	if err != nil {
		return err
	}
	defer closeFD(directory)
	if err := unix.Unlinkat(directory, name, 0); err != nil && !errors.Is(err, unix.ENOENT) {
		return err
	}
	return unix.Fsync(directory)
}
